<!-- Modal Verifikasi -->
<div id="modal-verifikasi" class="fixed inset-0 bg-gray-800 bg-opacity-50 flex items-center justify-center hidden z-50">
    <form method="POST" action="{{ url('/laporan/verifikasi-revisi') }}" id="form-verifikasi"
        class="bg-white rounded-lg shadow-2xl p-6 w-full max-w-7xl max-h-[95vh] overflow-y-auto border border-gray-300">
        @csrf
        <h2 class="text-2xl font-bold text-blue-600 mb-4">Verifikasi SPJ GU</h2>

        <input type="hidden" name="id" id="verifikasi-laporan-id">

        <div class="flex flex-col lg:flex-row gap-6">
            <!-- Kiri: Detail, Checklist, Catatan -->
            <div class="lg:w-1/2 space-y-6 overflow-y-auto max-h-[70vh] pr-1">
                <!-- Informasi Laporan -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 bg-gray-50 p-4 border rounded-lg text-sm text-gray-800">
                    <div><strong class="inline-block w-28">PPTK</strong>: <span id="info-pptk">-</span></div>
                    <div><strong class="inline-block w-28">Jenis</strong>: <span id="info-jenis">-</span></div>
                    <div><strong class="inline-block w-28">Kegiatan</strong>: <span id="info-kegiatan">-</span></div>
                    <div><strong class="inline-block w-28">Sub Kegiatan</strong>: <span id="info-subkegiatan">-</span></div>
                    <div><strong class="inline-block w-28">Rekening</strong>: <span id="info-rekening">-</span></div>
                    <div><strong class="inline-block w-28">Periode</strong>: <span id="info-periode">-</span></div>
                    <div><strong class="inline-block w-28">Pagu</strong>: <span id="info-pagu">-</span></div>
                    <div><strong class="inline-block w-28">Anggaran</strong>: <span id="info-anggaran">-</span></div>
                </div>

                <!-- Checklist -->
                <div>
                    <p class="font-semibold text-gray-800 mb-2">Checklist Dokumen:</p>
                    <ul id="checklist-items" class="space-y-3">
                        <!-- Checklist items generated by JS -->
                    </ul>
                </div>

                <!-- Catatan -->
                <div id="catatan-container" class="hidden">
                    <label for="catatan" class="block font-medium text-sm text-gray-800 mb-1 mt-4">Catatan (wajib diisi jika revisi):</label>
                    <textarea name="catatan" id="catatan" rows="4"
                        class="w-full border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-400"></textarea>
                </div>
            </div>

            <!-- Kanan: Preview PDF -->
            <div class="lg:w-1/2 flex flex-col">
                <p class="font-semibold text-gray-800 mb-2">File Laporan:</p>
                <div class="bg-white rounded border border-gray-200 text-sm text-gray-700 h-full flex flex-col shadow max-h-[70vh]">
                    <div class="p-2 border-b border-gray-200 flex justify-between items-center bg-gray-50">
                        <span class="text-sm">Preview PDF</span>
                        <div class="space-x-2">
                            <button type="button" onclick="zoomPdf('in')" class="px-2 py-1 bg-gray-200 rounded hover:bg-gray-300 text-sm">+</button>
                            <button type="button" onclick="zoomPdf('out')" class="px-2 py-1 bg-gray-200 rounded hover:bg-gray-300 text-sm">−</button>
                        </div>
                    </div>
                    <div id="pdf-viewer-container" class="flex-1 overflow-auto p-2">
                        <canvas id="pdf-canvas" class="w-full h-auto border border-gray-100"></canvas>
                    </div>
                    <div class="flex justify-between mt-2 px-2 pb-2">
                        <button type="button" id="prev-page" class="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300" onclick="changePage(-1)">Previous</button>
                        <button type="button" id="next-page" class="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300" onclick="changePage(1)">Next</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Tombol Aksi -->
        <div class="mt-6 flex justify-end gap-3">
            <button type="button" onclick="document.getElementById('modal-verifikasi').classList.add('hidden')"
                class="px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400">Tutup</button>
            <button type="submit" id="revisi-btn" name="action" value="revisi"
                class="px-4 py-2 bg-yellow-500 text-white rounded hover:bg-yellow-600 hidden">Revisi</button>
            <button type="submit" id="verifikasi-btn" name="action" value="verifikasi"
                class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700" disabled>Verifikasi Laporan</button>
        </div>
    </form>
</div>

@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>
<script>
let pdfZoom = 1, pdfDoc = null, currentPage = 1;

function zoomPdf(direction) {
    if (direction === 'in') pdfZoom += 0.1;
    else if (direction === 'out' && pdfZoom > 0.3) pdfZoom -= 0.1;
    renderPage(currentPage);
}
document.getElementById('form-verifikasi').addEventListener('submit', function (e) {
    const action = document.activeElement.value;
    const catatan = document.getElementById('catatan').value.trim();

    if (action === 'revisi') {
        if (catatan === '' || catatan === '-') {
            e.preventDefault();
            alert('Catatan wajib diisi untuk revisi!');
            document.getElementById('catatan').focus();
        }
    }
});


function renderPage(pageNumber) {
    pdfDoc.getPage(pageNumber).then(page => {
        const canvas = document.getElementById('pdf-canvas');
        const context = canvas.getContext('2d');
        const viewport = page.getViewport({ scale: pdfZoom });

        canvas.height = viewport.height;
        canvas.width = viewport.width;

        page.render({
            canvasContext: context,
            viewport: viewport
        });
    });
}
document.getElementById('form-verifikasi').addEventListener('submit', function (e) {
    const action = document.activeElement.value;
    const catatan = document.getElementById('catatan').value.trim();

    if (action === 'revisi') {
        if (catatan === '' || catatan === '-') {
            e.preventDefault();
            alert('Catatan wajib diisi untuk revisi!');
            document.getElementById('catatan').focus();
        }
    }
});


function loadPdf(url) {
    pdfjsLib.getDocument(url).promise.then(pdf => {
        pdfDoc = pdf;
        currentPage = 1;
        renderPage(currentPage);
    });
}
document.getElementById('form-verifikasi').addEventListener('submit', function (e) {
    const action = document.activeElement.value;
    const catatan = document.getElementById('catatan').value.trim();

    if (action === 'revisi') {
        if (catatan === '' || catatan === '-') {
            e.preventDefault();
            alert('Catatan wajib diisi untuk revisi!');
            document.getElementById('catatan').focus();
        }
    }
});


function changePage(direction) {
    if (pdfDoc) {
        const totalPages = pdfDoc.numPages;
        currentPage += direction;
        if (currentPage < 1) currentPage = 1;
        else if (currentPage > totalPages) currentPage = totalPages;
        renderPage(currentPage);
    }
}
document.getElementById('form-verifikasi').addEventListener('submit', function (e) {
    const action = document.activeElement.value;
    const catatan = document.getElementById('catatan').value.trim();

    if (action === 'revisi') {
        if (catatan === '' || catatan === '-') {
            e.preventDefault();
            alert('Catatan wajib diisi untuk revisi!');
            document.getElementById('catatan').focus();
        }
    }
});

function verifikasiLaporan(data) {
    document.getElementById('verifikasi-laporan-id').value = data.id;
    document.getElementById('info-pptk').innerText = data.pptk?.role ?? '-';
    document.getElementById('info-jenis').innerText = data.jenis_belanja;
    document.getElementById('info-kegiatan').innerText = data.kegiatan?.nama_kegiatan ?? '-';
    document.getElementById('info-subkegiatan').innerText = data.subkegiatan?.nama_subkegiatan ?? '-';
    document.getElementById('info-rekening').innerText = data.rekening_kegiatan;
    document.getElementById('info-periode').innerText = data.periode;
    document.getElementById('info-pagu').innerText = 'Rp' + new Intl.NumberFormat().format(data.nominal_pagu);
    document.getElementById('info-anggaran').innerText = 'Rp' + new Intl.NumberFormat().format(data.nominal);

    const checklistContainer = document.getElementById('checklist-items');
    checklistContainer.innerHTML = '';

    const checklistMap = {
        'SPJ GU': ['A2', 'Surat Pesanan', 'BAST', 'Nota/Kwitansi', 'Bukti Setoran Pajak'],
        'SPJ GU Tunai': ['A2', 'SPT', 'SPD', 'Tanda Terima', 'Notulen', 'Dokumentasi', 'Undangan'],
        'Belanja Tenaga Ahli': ['A2 (yang ada ppn pph)', 'Tanda Terima/Kuitansi', 'Daftar Laporan Harian', 'Upload Hasil Pekerjaan (jpg/pdf)', 'SPK'],
        'Belanja Jasa THL': ['A2', 'Tanda Terima/Kuitansi', 'Absensi', 'SK THL'],
        'LS': ['invoice', 'permohonan pembayaran', 'Berita acara pembayaran', 'Surat Perjanjian Kontrak', 'BA Pemeriksaan dan serah terima hasil pekerjaan', 'BA Penyerahan hasil pekerjaan', 'BA Penerimaan Barang', 'BA Penyerahan Barang', 'Faktur Pajak', 'Surat Pesanan Barang']
    };

    (checklistMap[data.jenis_belanja] || []).forEach(item => {
        const li = document.createElement('li');
        li.innerHTML = `
            <label class="flex items-center space-x-2 hover:bg-blue-100 p-2 rounded transition">
                <input type="checkbox" name="checklist[]" value="${item}" class="spj-checklist accent-blue-500" onchange="updateChecklistState()">
                <span>${item}</span>
            </label>
        `;
        checklistContainer.appendChild(li);
    });

    if (data.file_path) {
        const url = `{{ asset('storage') }}/${data.file_path}`;
        loadPdf(url);
    }

    document.getElementById('modal-verifikasi').classList.remove('hidden');
}
document.getElementById('form-verifikasi').addEventListener('submit', function (e) {
    const action = document.activeElement.value;
    const catatan = document.getElementById('catatan').value.trim();

    if (action === 'revisi') {
        if (catatan === '' || catatan === '-') {
            e.preventDefault();
            alert('Catatan wajib diisi untuk revisi!');
            document.getElementById('catatan').focus();
        }
    }
});

function updateChecklistState() {
    const checkboxes = document.querySelectorAll('.spj-checklist');
    const verifikasiBtn = document.getElementById('verifikasi-btn');
    const revisiBtn = document.getElementById('revisi-btn');
    const catatanContainer = document.getElementById('catatan-container');
    const catatanField = document.getElementById('catatan');

    const allChecked = Array.from(checkboxes).every(cb => cb.checked);

    if (allChecked) {
        verifikasiBtn.disabled = false;
        revisiBtn.classList.add('hidden');
        catatanContainer.classList.add('hidden');
        catatanField.value = '-'; // Auto isi catatan dengan "-"
    } else {
        verifikasiBtn.disabled = true;
        revisiBtn.classList.remove('hidden');
        catatanContainer.classList.remove('hidden');
        if (catatanField.value.trim() === '-' || catatanField.value.trim() === '') {
            catatanField.value = '';
        }
    }
}
document.getElementById('form-verifikasi').addEventListener('submit', function (e) {
    const action = document.activeElement.value;
    const catatan = document.getElementById('catatan').value.trim();

    if (action === 'revisi') {
        if (catatan === '' || catatan === '-') {
            e.preventDefault();
            alert('Catatan wajib diisi untuk revisi!');
            document.getElementById('catatan').focus();
        }
    }
});

</script>
@endpush
